# Generated by Django 4.2.7 on 2024-05-23 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='conversation_images/')),
                ('audio', models.FileField(blank=True, null=True, upload_to='conversation_audios/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, max_length=400, null=True)),
                ('event', models.CharField(blank=True, max_length=400, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('missed', 'Missed'), ('doing', 'Doing'), ('finished', 'Finished'), ('canceled', 'Canceled')], default='doing', max_length=10)),
                ('privacy', models.CharField(choices=[('open', 'Open'), ('secret', 'Secret'), ('grouply', 'Grouply')], default='open', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('financial_help', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_changed', models.BooleanField(default=False)),
                ('problem', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaskContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('audio', 'Audio')], max_length=10, verbose_name='Content Type')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Text Content')),
                ('image', models.ImageField(blank=True, null=True, upload_to='task_images/', verbose_name='Image Content')),
                ('audio', models.FileField(blank=True, null=True, upload_to='task_audios/', verbose_name='Audio Content')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='task.task', verbose_name='Task')),
            ],
            options={
                'verbose_name': 'Task Content',
                'verbose_name_plural': 'Task Contents',
            },
        ),
    ]
