# Generated by Django 4.2.7 on 2024-05-23 08:26

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='company/', verbose_name='Logotip')),
                ('name', models.CharField(blank=True, max_length=300, null=True, verbose_name='Korxona Nomi')),
                ('address', models.CharField(blank=True, max_length=300, null=True, verbose_name='Korxona manzili')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Korxona haqida batafsil...')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='Lavozim turi')),
            ],
            options={
                'verbose_name': 'Position',
                'verbose_name_plural': 'Positions',
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Bolim nomi')),
            ],
            options={
                'verbose_name': 'Sector',
                'verbose_name_plural': 'Sectors',
            },
        ),
        migrations.CreateModel(
            name='Xodim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shior', models.CharField(blank=True, max_length=195, null=True, verbose_name='Shior')),
                ('main_task', models.TextField(blank=True, null=True, verbose_name='Asosiy vazifa')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Tugilgan sana')),
                ('phone_number', models.CharField(blank=True, max_length=14, null=True, validators=[django.core.validators.RegexValidator('^\\+998\\d{9}$', 'Telefon raqami noto‘g‘ri formatda')], verbose_name='Telefon raqami')),
                ('photo', models.ImageField(default='photos/1.png', upload_to='photos', verbose_name='Rasmi')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Xodim',
                'verbose_name_plural': 'Xodimlar',
            },
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='notes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('label', models.CharField(blank=True, choices=[('eng muhim', 'Eng muhim'), ('muhim', 'Muhim'), ('muhim emas', 'Muhim emas'), ("o'rta", "O'rta"), ('darajasiz', 'Darajasiz')], max_length=30, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shior', models.CharField(blank=True, max_length=195, null=True, verbose_name='Shior')),
                ('main_task', models.TextField(blank=True, null=True, verbose_name='Asosiy vazifa')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Tugilgan sana')),
                ('phone_number', models.CharField(blank=True, max_length=14, null=True, validators=[django.core.validators.RegexValidator('^\\+998\\d{9}$', 'Telefon raqami noto‘g‘ri formatda')], verbose_name='Telefon raqami')),
                ('photo', models.ImageField(default='photos/1.png', upload_to='photos', verbose_name='Rasmi')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Manager',
                'verbose_name_plural': 'Managerlar',
            },
        ),
        migrations.CreateModel(
            name='Direktor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shior', models.CharField(blank=True, max_length=195, null=True, verbose_name='Shior')),
                ('main_task', models.TextField(blank=True, null=True, verbose_name='Asosiy vazifa')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Tugilgan sana')),
                ('phone_number', models.CharField(blank=True, max_length=14, null=True, validators=[django.core.validators.RegexValidator('^\\+998\\d{9}$', 'Telefon raqami noto‘g‘ri formatda')], verbose_name='Telefon raqami')),
                ('photo', models.ImageField(default='photos/1.png', upload_to='photos', verbose_name='Rasmi')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Direktor',
                'verbose_name_plural': 'Direktorlar',
            },
        ),
        migrations.CreateModel(
            name='Boshqalar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shior', models.CharField(blank=True, max_length=195, null=True, verbose_name='Shior')),
                ('main_task', models.TextField(blank=True, null=True, verbose_name='Asosiy vazifa')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Tugilgan sana')),
                ('phone_number', models.CharField(blank=True, max_length=14, null=True, validators=[django.core.validators.RegexValidator('^\\+998\\d{9}$', 'Telefon raqami noto‘g‘ri formatda')], verbose_name='Telefon raqami')),
                ('photo', models.ImageField(default='photos/1.png', upload_to='photos', verbose_name='Rasmi')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Boshqalar',
                'verbose_name_plural': 'Boshqalar',
            },
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shior', models.CharField(blank=True, max_length=195, null=True, verbose_name='Shior')),
                ('main_task', models.TextField(blank=True, null=True, verbose_name='Asosiy vazifa')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Tugilgan sana')),
                ('phone_number', models.CharField(blank=True, max_length=14, null=True, validators=[django.core.validators.RegexValidator('^\\+998\\d{9}$', 'Telefon raqami noto‘g‘ri formatda')], verbose_name='Telefon raqami')),
                ('photo', models.ImageField(default='photos/1.png', upload_to='photos', verbose_name='Rasmi')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin',
                'verbose_name_plural': 'Adminlar',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='rank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.position', verbose_name='Lavozim'),
        ),
        migrations.AddField(
            model_name='user',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.sector', verbose_name='Bo‘lim'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
