# Generated by Django 4.2.7 on 2024-06-12 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_admin_user_alter_boshqalar_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, default='1.png', null=True, upload_to='user/'),
        ),
    ]
